/**
 * Image generation using Gemini 3 Pro and DALL-E 3.
 * Supports provider resolution through BYOK chain.
 */

import { GoogleGenerativeAI } from '@google/generative-ai';
import { uploadToS3, generateS3Key } from '../s3';
import { getApiKeyForProvider } from './providers';

export interface ImageGenerationResult {
  imageUrl: string;
  imageBase64?: string;
  mimeType: string;
  model: string;
}

/**
 * Generate image using Gemini 3 Pro Image Preview
 */
async function generateWithGemini(
  prompt: string,
  apiKey: string
): Promise<ImageGenerationResult> {
  const genAI = new GoogleGenerativeAI(apiKey);
  const model = genAI.getGenerativeModel({
    model: 'gemini-3-pro-image-preview',
  });

  const result = await model.generateContent({
    contents: [{ role: 'user', parts: [{ text: prompt }] }],
  });

  const response = result.response;
  const imagePart = response.candidates?.[0]?.content?.parts?.find(
    (part: { inlineData?: { mimeType?: string } }) =>
      part.inlineData?.mimeType?.startsWith('image/')
  );

  if (!imagePart?.inlineData) {
    throw new Error('No image generated by Gemini');
  }

  return {
    imageBase64: imagePart.inlineData.data,
    mimeType: imagePart.inlineData.mimeType || 'image/png',
    model: 'gemini-3-pro-image-preview',
  } as ImageGenerationResult;
}

/**
 * Generate image using DALL-E 3
 */
async function generateWithDallE(
  prompt: string,
  apiKey: string,
  options?: { size?: string; quality?: string }
): Promise<ImageGenerationResult> {
  const response = await fetch('https://api.openai.com/v1/images/generations', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'dall-e-3',
      prompt,
      n: 1,
      size: options?.size || '1792x1024',
      quality: options?.quality || 'standard',
      response_format: 'b64_json',
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`DALL-E 3 generation failed: ${response.status} - ${error}`);
  }

  const data = await response.json();
  const imageData = data.data?.[0];

  if (!imageData?.b64_json) {
    throw new Error('No image generated by DALL-E');
  }

  return {
    imageBase64: imageData.b64_json,
    mimeType: 'image/png',
    model: 'dall-e-3',
  } as ImageGenerationResult;
}

/**
 * Generate image and upload to S3.
 * Uses BYOK provider resolution to find available API keys.
 * Fallback: Gemini → DALL-E → error
 */
export async function generateImage(
  prompt: string,
  studioId: string,
  preferredModel?: string
): Promise<ImageGenerationResult> {
  const errors: string[] = [];

  // Determine provider order based on preference
  type ProviderEntry = {
    name: string;
    provider: 'google' | 'openai';
    generate: (prompt: string, key: string) => Promise<ImageGenerationResult>;
  };

  const providers: ProviderEntry[] = preferredModel === 'dall-e-3'
    ? [
        { name: 'DALL-E 3', provider: 'openai', generate: generateWithDallE },
        { name: 'Gemini 3 Pro', provider: 'google', generate: generateWithGemini },
      ]
    : [
        { name: 'Gemini 3 Pro', provider: 'google', generate: generateWithGemini },
        { name: 'DALL-E 3', provider: 'openai', generate: generateWithDallE },
      ];

  for (const entry of providers) {
    try {
      const apiKey = await getApiKeyForProvider(studioId, entry.provider);
      if (!apiKey) {
        errors.push(`${entry.name}: pas de cle API disponible`);
        continue;
      }

      console.log(`[ImageGen] Generating with ${entry.name}...`);
      const result = await entry.generate(prompt, apiKey);

      // Upload to S3
      if (result.imageBase64) {
        const buffer = Buffer.from(result.imageBase64, 'base64');
        const ext = result.mimeType === 'image/png' ? 'png' : 'jpg';
        const filename = `generated-${Date.now()}.${ext}`;
        const s3Key = generateS3Key(filename, studioId);
        const s3Result = await uploadToS3(buffer, s3Key, result.mimeType);

        return {
          imageUrl: s3Result.url,
          mimeType: result.mimeType,
          model: result.model,
        };
      }

      return result;
    } catch (error) {
      const msg = error instanceof Error ? error.message : 'Unknown error';
      console.warn(`[ImageGen] ${entry.name} failed:`, msg);
      errors.push(`${entry.name}: ${msg}`);
    }
  }

  throw new Error(
    `Aucun provider d'image disponible. Erreurs: ${errors.join('; ')}`
  );
}
